#Location of Spring application context:
contextLocation: "classpath*:context/appContext.xml"

#Used for static resource serving in development mode
#assets:
#  overrides:
#    /: ../../wf-console/src/main/resources/assets/

#Configuration of actors served by this server:
actorConfig:
  actorPreferences:
    - id: "default"
      timeoutPolicies:
#        PROCESS_START_TO_CLOSE: "skipping holidays 1 day timeout"
#        PROCESS_SCHEDULE_TO_START: "timeout 15 seconds"
#        PROCESS_SCHEDULE_TO_CLOSE: "timeout 15 seconds"
        TASK_START_TO_CLOSE: "TIMEOUT: 15 seconds"
#        TASK_SCHEDULE_TO_START: "timeout 15 seconds"
#        TASK_SCHEDULE_TO_CLOSE: "timeout 15 seconds"
#        TASK_POLL_TO_COMMIT: "timeout 15 seconds"
#        TASK_RELEASE_TO_COMMIT: "timeout 15 seconds"

#List of expiration policies available for actors:
#  expirationPolicies:
#    - name: "timeout 15 seconds"
#      className: "ru.taskurotta.server.config.expiration.impl.TimeoutPolicy"
#      properties:
#        timeout: 15
#        timeUnit: "SECONDS"
#    - name: "retriable 60 seconds timeout"
#      className: "ru.taskurotta.server.config.expiration.impl.TimeoutWithFixedRetryPolicy"
#      properties:
#        timeout: 60
#        timeUnit: "SECONDS"
#        retry: 10
#    - name: "skipping holidays 1 day timeout"
#      className: "ru.taskurotta.server.config.expiration.impl.SkippingHolidaysTimeoutPolicy"
#      properties:
#        timeout: "1 days"
#        location: "target/classes/holidays.txt"
#        format: "yyyy-MM-dd"

#Task server common properties (will be available as placeholders in spring context):
properties:
  pollDelay: 10
  pollDelayUnit: "SECONDS"
  retryTimes: 10
  recovery.schedule: "*/35 * * * * ?"
  recovery.period: 2
  recovery.period.unit: "DAYS"
  recovery.timeStep: 1
  recovery.timeStep.unit: "DAYS"

#Http server configuration:
logging:
    level: WARN
    loggers:
        ru.taskurotta: INFO
        ru.taskurotta.console: DEBUG
#        ru.taskurotta.dropwizard.resources: DEBUG
#        ru.taskurotta.backend.queue: DEBUG
#        ru.taskurotta.backend: INFO
#        ru.taskurotta.server.recovery: DEBUG
        com.yammer: INFO
    file:
        enabled: true
        archive: true
        currentLogFilename: ./target/logs/service.log
        archivedLogFilenamePattern: ./target/logs/service-%d.log.gz
http:
    rootPath: "/rest/*"
    gzip:
        enabled: false
    requestLog:
        file:
            enabled: true
            archive: true
            currentLogFilename: ./target/logs/requests.log
            archivedLogFilenamePattern: ./target/logs/service-%d.log.gz
#config can be extended here
#http://dropwizard.codahale.com/manual/core/#configuration-defaults